### ISSUE TITLE
TurboJPEG - Push changes to upstream

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/MIVisionX#1051]
rocAL requires a particular version of TurboJPEG which is only available on - git clone -b 2.0.6.1 https://github.com/rrawther/libjpeg-turbo.git

This is causing issues with DevOPS as they install TurboJPEG from publicly available release. Which fails with 

```
/usr/bin/ld: /opt/rocm/lib/librocal.so: undefined reference to `tjDecompress2_partial_scale@TURBOJPEG_1.0'
/usr/bin/ld: /opt/rocm/lib/librocal.so: undefined reference to `tjDecompress2_partial@TURBOJPEG_1.0'
collect2: error: ld returned 1 exit status
```

To solve this we need to push the changes we require to upstream.

**Comment by kiritigowda** [comment]
@rrawther any updates on TurboJPEG?

**Comment by rrawther** [comment]
Hi @afzpatel : To get rid of this, we need to do some work in the rocAL code so it doesn't use that API. Beause of no available resource to work on this, it is deferred. we will work on this in future.

**Comment by Madouura** [comment]
I've noticed a similar problem with ``rapidjson``.
``rapidjson`` just needs a more up-to-date git version instead of release version, however with this we need an entire separate repo and version.

**Comment by kiritigowda** [comment]
TurboJPEG dependencies updated and rocAL moved out of MIVisionX as an independent component - https://github.com/ROCm/rocAL
