### ISSUE TITLE
Setup - ROCm 6.2 Updates

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/MIVisionX#1171]
* Install all libraries with error check?
* Option to reinstall existing packages?
* Option for a cached log to debug?

**Comment by kiritigowda** [comment]
@paveltc - We need to discuss the possibility of having the `Package Upgrade` option in setup?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 @rrawther @hansely @paveltc @asalmanp - please add any feature or options you feel is missing or will enhance the existing setup scripts for 6.0 release.

**Comment by kiritigowda** [comment]
* Docker missing - libcanberra-gtk-module

**Comment by LakshmiKumar23** [comment]
@kiritigowda Please add this library as a pre-req to ffmpeg. Needed on some MI300 systems
```
sudo apt install libswresample-dev
```

**Comment by kiritigowda** [comment]
Use package manager to install `RPP` package instead of building from source.

**Comment by kiritigowda** [comment]
Setup variants - 

* developer setup - with source install for devs
* Quick setup - package install

**Comment by kiritigowda** [comment]
Phase 1 - merged to master with #1318

**Comment by kiritigowda** [comment]
Phase 2 fixes #1331

**Comment by kiritigowda** [comment]
@LakshmiKumar23 @paveltc -- can you test the develop branch and comment on this issue.
