### ISSUE TITLE
Broken urls to samples in MIVisionX documentation

### ISSUE THREAD

**Issue by pibesk** [ROCm/MIVisionX#1292]
On index page of documentation - https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/index.html
When we scroll to **Applications** all urls in this section return  404 error 
![obraz](https://github.com/ROCm/MIVisionX/assets/43028488/0e1c7485-8451-4f1f-88c0-9f33c8bd7c59)

If we click from left menu **Applications** we get page with working urls.

**Comment by kiritigowda** [comment]
@pibesk thanks for bringing this to our attention. We will get this issue fixed.

**Comment by randyh62** [comment]
> @randyh62 let me know if this issue is resolved; we can close this issue.

It is fixed.

**Comment by kiritigowda** [comment]
@pibesk -- thanks for bringing this to our attention; we have resolved the issues. Please reopen this issue if you find any other unexpected behavior.
